Zz897426182/RealTimeFaceCompare

Distribution/pom.xml
Distribution/src/main/assembly/assembly.xml
FtpServer/pom.xml
pom.xml

创建模块  Distribution，用来收集bin 目录conf 目录，jar 包等资源文件。

创建模块  Distribution

---

FtpServer/src/main/java/com/hzgc/ftpserver/kafka/consumer/WorkerThread.java
FtpServer/src/main/java/com/hzgc/ftpserver/kafka/ftp/KafkaSTOR.java
FtpServer/src/main/java/com/hzgc/ftpserver/util/Utils.java

修改rowkey的拼装，优化小图的处理逻辑：同一场景下可接收与存储多张小图。

rowKey拼装，优化小图接收处理

---

Dubbo/src/main/java/com/hzgc/dubbo/staticrepo/ObjectInfoHandler.java
HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoInnerHandler.java

1，删除dubbo中对内的接口，对内的接口放在各个模块下面。
2，增删改传入的参数需要相应的进行修改。

接口定义的地方修改以及接口参数修改。

---

Dubbo/src/main/java/com/hzgc/dubbo/staticrepo/ObjectInfoHandler.java

1,修改对外提供的根据图片提取特征值的接口的返回值为String。

修改根据图片提取特征值接口的返回值。

---

FtpServer/src/main/java/com/hzgc/ftpserver/util/Utils.java

修改rowKey拼装，修改后rowKey的长度始终为8的倍数，优化小图接收处理

修改rowKey拼装，修改后rowKey的长度始终为8的倍数，优化小图接收处理

---

.gitignore
Dubbo/pom.xml
Dubbo/src/main/java/com/hzgc/dubbo/staticrepo/ObjectInfoHandler.java
Dubbo/src/main/java/com/hzgc/dubbo/staticrepo/SearchRecordHandler.java

1,修改dubbo 模块pom文件，用来生成javadocs。
2,staticrepo 包中的注释的不规范地方。

1,修改dubbo 模块pom文件，用来生成javadocs。.

---

Dubbo/src/main/java/com/hzgc/dubbo/staticrepo/ObjectInfoHandler.java

1,查询的接口中，需要添加字段，人员的名字。

---

.gitignore
Dubbo/src/main/java/com/hzgc/dubbo/staticrepo/ObjectInfoHandler.java
FtpServer/src/main/java/com/hzgc/ftpserver/util/FtpUtil.java
HBase/pom.xml
HBase/src/main/java/com/hzgc/hbase/staticrepo/ElasticSearchHelper.java
HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java
HBase/src/main/java/com/hzgc/hbase/util/HBaseHelper.java
HBase/src/main/java/com/hzgc/hbase/util/HBaseUtil.java
HBase/src/main/resources/hbase-site.xml
HBase/src/test/java/com/hzgc/hbase/staticreposuite/Image2Byte2Image.java
HBase/src/test/java/com/hzgc/hbase/staticreposuite/StaticRepoUtilSuite.java

完成增删改查，根据rowkey返回图片

---

Distribution/pom.xml
Distribution/src/main/assembly/assembly.xml

修改好distribution 模块，收集各个子模块下面的配置文件和jar包

收集jar包和conf 文件模块distribution 的修改。

---

HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java

增加根据姓名查询结果代码

---

Dubbo/src/main/java/com/hzgc/dubbo/staticrepo/ObjectInfoHandler.java
Dubbo/src/main/java/com/hzgc/dubbo/staticrepo/PSearchArgsModel.java
HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java

1，封装传过来的参数， 
2，修改对应的处理插入历史记录的函数，原先的少了存图片这一个过程。

搜索参数封装类以及插入历史记录少了图片的内容。

---

HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java
HBase/src/test/java/com/hzgc/hbase/staticreposuite/StaticRepoUtilSuite.java

修改getphotobyrowkey方法

---

Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/CapturePictureSearchService.java
Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/DynamicObject.java
Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/DynamicPhotoService.java
FtpServer/src/main/resources/consumer-face.properties
FtpServer/src/main/resources/consumer-json.properties
FtpServer/src/main/resources/consumer-picture.properties
FtpServer/src/main/resources/table-hbase.properties
HBase/pom.xml
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/DynamicPhotoServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/DynamicTable.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/FilterByRowkey.java

增加动态库实现类，修改FTP配置文件

---

Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/CapturedPicture.java
Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/PictureType.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java

修改CapturePictureSearchServiceImpl实现类

修改CapturePictureSearchServiceImpl实现类

---

Dubbo/src/main/java/com/hzgc/dubbo/staticrepo/ObjectInfoTable.java
HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java

1,添加一个table类，里面存放表名，列族名，列明等，
方便后续版本改标的名字，以及方便和平台组交流维护。
2，对应着table类，修改添加修改和删除的对应属性。
3，修改更新接口，更新接口里面没有在更新的时候更新时间。"

添加ObjectInfoTable类

---

Dubbo/src/main/java/com/hzgc/dubbo/staticrepo/SearchRecordHandler.java
HBase/src/main/java/com/hzgc/hbase/staticrepo/SearchRecordHandlerImpl.java
HBase/src/test/java/com/hzgc/hbase/device/Test.java
HBase/src/test/java/com/hzgc/hbase/staticreposuite/StaticRepoUtilSuite.java

fix the method getRocordOfObjectInfo

fix getRocordOfObjectInfo

---

HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/DynamicPhotoServiceImpl.java

修改动态库接口实现方法

---

HBase/src/main/resources/spring-context.xml

向dubbo 中注册Hbase 相关操作的接口。

---

HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/FilterByRowkey.java

添加search实现方法

---

Distribution/bin/start-consumer.sh

创建ConsumerGroupsMain的脚本

---

HBase/src/test/java/com/hzgc/hbase/device/DeviceServiceSuite.java

测试DeviceServiceImpl

---

FtpServer/src/main/java/com/hzgc/ftpserver/kafka/consumer/ConsumerHandlerThread.java
FtpServer/src/main/java/com/hzgc/ftpserver/kafka/consumer/WorkerThread.java
FtpServer/src/main/java/com/hzgc/ftpserver/kafka/consumer/face/FaceConsumerHandlerThread.java
FtpServer/src/main/java/com/hzgc/ftpserver/kafka/consumer/json/JsonConsumerHandlerThread.java
FtpServer/src/main/java/com/hzgc/ftpserver/kafka/consumer/picture2/PicConsumerHandlerThread.java
FtpServer/src/main/resources/consumer-face.properties
FtpServer/src/main/resources/consumer-json.properties
FtpServer/src/main/resources/consumer-picture.properties
FtpServer/src/main/resources/table-hbase.properties
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/FilterByRowkey.java

通过Ftp添加设备ID与时间戳到Hbase

---

HBase/src/main/java/com/hzgc/hbase/dynamicrepo/FilterByRowkey.java

修改filterByPlateNumber方法，增加判空操作

修改filterByPlateNumber方法，增加判空操作

---

HBase/src/main/java/com/hzgc/hbase/device/DeviceServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/FilterByRowkey.java
HBase/src/main/resources/es-config.properties
HBase/src/test/java/com/hzgc/hbase/device/DeviceServiceSuite.java
HBase/src/test/java/com/hzgc/hbase/device/FilterByRowKeySuit.java

添加DeviceUtilImpl的测试类

---

Dubbo/src/main/java/com/hzgc/dubbo/staticrepo/ObjectInfoTable.java
HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java
HBase/src/test/java/com/hzgc/hbase/staticreposuite/EsDataSuite.java
HBase/src/test/java/com/hzgc/hbase/staticreposuite/SearchApiSuite.java
HBase/src/test/java/com/hzgc/hbase/staticreposuite/SearchPicByPic.java

1，实现静态信息库以图搜图接口。
2，实现往HBase 和Es 中插入测试数据。

实现静态信息库以图搜图接口

---

HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java
HBase2Es/src/main/java/com/hzgc/hbase2es/coproccessor/PersonRepo2EsObserver.java
HBase2Es/src/main/java/com/hzgc/hbase2es/coproccessor/StaticRepo2EsObserver.java

1,修复同步到Es数据中，没有包含理由的问题。
2，给动态信息建立的es索引，添加一个时间段的字段，用来进行按照时间段和开始时间和结束时间进行查询。
3，修复静态信息库查询接口中性别为空的时候的默认值。

修复Bug----ES

---

HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoInnerHandlerImpl.java

添加ObjectInfoInnerHandlerImpl接口判断

添加ObjectInfoInnerHandlerImpl接口判断

---

Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/PictureType.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java
HBase/src/test/java/com/hzgc/hbase/dynamicrepo/CapturePictureTest.java
Util/src/main/java/com.hzgc.util/ListUtils.java

增加动态库SearchResult对象排序方法

---

Dubbo/src/main/java/com/hzgc/dubbo/staticrepo/ObjectInfoTable.java
HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java
HBase/src/main/java/com/hzgc/hbase/staticrepo/SearchRecordHandlerImpl.java
HBase/src/test/java/com/hzgc/hbase/staticreposuite/SearchApiSuite.java
HBase/src/test/java/com/hzgc/hbase/staticreposuite/StaticRepoUtilSuite.java
HBase2Es/src/main/java/com/hzgc/hbase2es/coproccessor/StaticRepo2EsObserver.java
HBase2Es/src/test/java/com/hzgc/hbase2es/PingYinUtilSuite.java
Util/src/main/java/com.hzgc.util/PinYinUtil.java

优化根据姓名和创建者姓名查询静态信息库内容。
把姓名和创建者姓名转换成拼音来进行查询。

优化根据姓名和创建者姓名查询静态信息库内容。

---

HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoInnerHandlerImpl.java

添加一个更新对象信息库中的uptatime 的接口。

---

HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java

根据平台id 和身份证号，可以得到一个人的精确的数据。

---

HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/DynamicPhotoServiceImpl.java
HBase/src/test/java/com/hzgc/hbase/dynamicrepo/CapturePictureTest.java
Util/src/main/java/com.hzgc.util/ObjectListSort/ListUtils.java
Util/src/main/java/com.hzgc.util/ObjectListSort/SortParam.java
Util/src/main/java/com.hzgc.util/StringUtil.java

增加动态库SearchResult对象排序与分页

---

Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/DynamicPhotoService.java
Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/SearchOption.java
HBase/pom.xml
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/DynamicPhotoServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/FilterByRowkey.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/RealTimeCompare.java
JNI/src/main/java/com/hzgc/jni/FaceFunction.java
Util/src/main/java/com.hzgc.util/ObjectListSort/ListUtils.java

代码微调，解决冲突问题

---

HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java
HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoInnerHandlerImpl.java
HBase/src/test/java/com/hzgc/hbase/staticreposuite/SearchByPkeys.java

修改getByPkeys接口

---

Distribution/bin/create-table.sh
Distribution/bin/start-consumer.sh
Distribution/bin/start-ftpserver.sh
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/FilterByRowkey.java
HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoInnerHandlerImpl.java

1，修改按照时间段查询的接口，
2，修改返回值中不必要的字段。

修复和优化动态信息库的接口。

---

HBase/src/test/java/com/hzgc/hbase/staticreposuite/SearchApiSuite.java
HBase/src/test/java/com/hzgc/hbase/staticreposuite/SearchByPkeys.java
HBase/src/test/java/com/hzgc/hbase/staticreposuite/StaticRepoUtilSuite.java
HBase2Es/src/main/java/com/hzgc/hbase2es/util/HBaseHelper.java

给表格添加snappy 压缩

---

Spark_Streaming/src/main/scala/com/hzgc/streaming/job/FaceRecognizeAlarmJob.scala

识别告警：时间更新子模块修改。

---

FtpServer/src/main/java/com/hzgc/ftpserver/util/FtpUtil.java

修改rowKey拼装

---

Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/DynamicPhotoService.java

优化代码：采用多线程批处理从HBase读取数据

---

Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/DynamicPhotoService.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/DynamicPhotoServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/FilterByRowkey.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/RealTimeCompare.java

新增查询某个设备下所有图片

---

HBase/src/main/java/com/hzgc/hbase/dynamicrepo/DynamicPhotoServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/RealTimeCompare.java

日志输出数据量和时间消耗

---

HBase/src/main/java/com/hzgc/hbase/dynamicrepo/DynamicPhotoServiceImpl.java

优化DynamicPhotoServiceImpl类

---

FtpServer/pom.xml
FtpServer/src/main/java/com/hzgc/ftpserver/kafka/consumer/WorkerThread.java
FtpServer/src/main/java/com/hzgc/ftpserver/util/FtpUtil.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java

FTP动态库数据同步ES

---

HBase/src/main/resources/sql/dynamic.sql

设置searchRes表TTL

---

HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java
HBase/src/test/java/com/hzgc/hbase/staticreposuite/EsDataSuite.java

1,修改有图片的情况下的过滤逻辑。

---

Distribution/bin/spilit-json-and-bulk-data-to-es.sh
HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java

脚本修复，意图搜素返回总记录数修复。

---

FtpServer/src/main/java/com/hzgc/ftpserver/kafka/consumer/WorkerThread.java

修改动态库信息同步ES，并添加日志信息

---

Distribution/bin/start-face-add-alarm-job.sh
Distribution/bin/start-face-offline-alarm-job.sh
Distribution/bin/start-face-recognize-alarm-job.sh
Distribution/src/main/assembly/assembly.xml
Spark_Streaming/src/main/scala/com/hzgc/streaming/job/FaceAddAlarmJob.scala
Spark_Streaming/src/main/scala/com/hzgc/streaming/job/FaceOffLineAlarmJob.scala
Spark_Streaming/src/main/scala/com/hzgc/streaming/job/FaceRecognizeAlarmJob.scala

告警任务优化[任务启动脚本，告警任务优化]（2017/9/9）

告警任务优化[任务启动脚本，告警任务优化]（2017/9/9）

---

FtpServer/src/main/java/com/hzgc/ftpserver/kafka/ftp/KafkaSTOR.java

Ftp中针对未知ipcID处理

---

FtpServer/src/main/java/com/hzgc/ftpserver/kafka/consumer/WorkerThread.java

优化动态库信息同步ES

---

HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java

1，修复根据姓名和创建者查询不到数据的情况。
2，修复修改对象类型key 时出错情况。

to fixed static bug 

---

HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/DynamicPhotoServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/ExportPicture.java

CapturedPicture对象set图片属性时判空

---

JNI/src/main/java/com/hzgc/jni/FaceFunction.java

FaceFunction类方法添加同步处理

---

FtpServer/src/main/java/com/hzgc/ftpserver/util/FtpUtil.java

添加通过rowkey解析文件路径方法

---

HBase/src/main/java/com/hzgc/hbase/device/WarnRuleServiceImpl.java

告警规则删除接口修改

---

HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java

1，不按照ES 根据姓名和创建者搜索的规则，而按照平台和测试组认定的规则来匹配。
2，修改新的引入的Bug ，修改后，创建者变成创建时间了。

匹配新的根据名字和创建者姓名查询的规则。

---

Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/SearchType.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/RealTimeCompare.java

1.查询设备抓拍历史首页直接返回图片，无需平台再次调用获取图片方法
2.增删注释

更新查询设备抓拍历史接口

---

Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/SearchFilter.java
Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/SearchOption.java
Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/SearchType.java
pom.xml

reformat code

---

FtpServer/src/main/java/com/hzgc/ftpserver/kafka/ftp/KafkaSTOR.java
FtpServer/src/main/java/com/hzgc/ftpserver/kafka/producer/FaceObject.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/RealTimeCompare.java
HBase/src/main/java/com/hzgc/hbase/putdata/GenerateImportFile.java
HBase/src/main/java/com/hzgc/hbase/staticrepo/ObjectInfoHandlerImpl.java
HBase/src/test/java/com/hzgc/hbase/staticreposuite/SearchPicByPic.java
JNI/src/main/java/com/hzgc/jni/FaceAttr.java
JNI/src/main/java/com/hzgc/jni/FaceExtract.java
JNI/src/main/java/com/hzgc/jni/FaceExtractImpl.java
JNI/src/main/java/com/hzgc/jni/FaceFunction.java
JNI/src/main/java/com/hzgc/jni/NativeFunction.java
JNI/src/main/java/com_hzgc_jni_NativeFunction.h

修改JNI模块：特征值与属性封装到FaceAttr对象，新增FaceObject对象

修改JNI模块：特征值与属性封装到FaceAttr对象，新增FaceObject对象

---

FtpServer/src/main/java/com/hzgc/ftpserver/local/LocalSTOR.java
FtpServer/src/main/java/com/hzgc/ftpserver/util/FileType.java
FtpServer/src/main/java/com/hzgc/ftpserver/util/FtpUtil.java
FtpServer/src/main/java/com/hzgc/ftpserver/util/IpAddressUtil.java
JNI/src/main/java/com/hzgc/jni/Attribute/Eyeglasses.java
JNI/src/main/java/com/hzgc/jni/Attribute/Gender.java
JNI/src/main/java/com/hzgc/jni/Attribute/HairColor.java
JNI/src/main/java/com/hzgc/jni/Attribute/HairStyle.java
JNI/src/main/java/com/hzgc/jni/Attribute/Hat.java
JNI/src/main/java/com/hzgc/jni/Attribute/Huzi.java
JNI/src/main/java/com/hzgc/jni/Attribute/Tie.java

JNI枚举类实现序列化

---

FtpServer/src/main/resources/consumer-feature.properties
FtpServer/src/main/resources/producer-over-ftp.properties

修改人：彭聪
修改内容：producer_over-ftp.properties&consumer-feature.properties 中value.deserializer&value.serializer配置项分别修改为自定义编解码器
所属模块：FTP
合入人：彭聪
合入时间：2017-10-31

Kafka生产者和消费者配置项分别修改为自定义编解码器

---

Dubbo/src/main/java/com/hzgc/dubbo/Attribute/AttributeCount.java
Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/CapturePictureSearchService.java
FtpServer/src/main/java/com/hzgc/ftpserver/local/LocalSTOR.java
FtpServer/src/main/java/com/hzgc/ftpserver/util/Download.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java

修改人：刘思阳
修改内容：新增从FTP服务器下载文件并转为字节数组方法；新增抓拍属性统计查询接口
所属模块：dubbo、Hbase、FTP
合入人：赵喆
合入时间：2017-11-4

新增从FTP服务器下载文件并转为字节数组方法；新增抓拍属性统计查询接口

---

Dubbo/src/main/java/com/hzgc/dubbo/Attribute/AttributeCount.java
Dubbo/src/main/java/com/hzgc/dubbo/Attribute/Eyeglasses.java
Dubbo/src/main/java/com/hzgc/dubbo/Attribute/Gender.java
Dubbo/src/main/java/com/hzgc/dubbo/Attribute/HairColor.java
Dubbo/src/main/java/com/hzgc/dubbo/Attribute/HairStyle.java
Dubbo/src/main/java/com/hzgc/dubbo/Attribute/Hat.java
Dubbo/src/main/java/com/hzgc/dubbo/Attribute/Huzi.java
Dubbo/src/main/java/com/hzgc/dubbo/Attribute/Tie.java
Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/CapturePictureSearchService.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java
HBase/src/main/resources/es-config.properties
JNI/src/main/java/com/hzgc/jni/FaceAttribute.java

修改人：刘思阳
修改内容：修改抓拍属性统计查询接口，修改jni属性类定义
所属模块：Doubbo、Hbase、JNI
合入人：赵喆
合入时间：2017-11-6

修改抓拍属性统计查询接口，修改jni属性类定义

---

Cluster/src/main/java/com/hzgc/cluster/consumer/PutDataToEs.java
Cluster/src/main/scala/com/hzgc/cluster/consumer/kafkaToParquet.scala
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/DynamicTable.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/FilterByRowkey.java
HBase/src/test/java/com/hzgc/hbase/device/CapturePictureCatchHistoryTest.java

修改人：陈柯
修改内容：统一ES字段名称并定义，添加抓拍历史接口的测试类
所属模块：Hbase
合入人：赵喆
合入时间：2017-11-6

统一ES字段名称并定义

---

FtpServer/src/main/java/com/hzgc/ftpserver/address/FtpAddressServiceImpl.java

修改人：彭聪
修改内容：删除FTP负载均衡代码
所属模块：FTP
合入人：赵喆
合入时间：2017-11-7

删除FTP负载均衡代码

---

HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/DynamicTable.java

修改内容：更新以图搜图过滤条件；删除多余类；合并了DynamicTable中的字段
所属模块：HBase
合入人：赵喆
合入时间：2017-11-7

以后要会使用命令提代码

---

HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CaptureHistory.java
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/RealTimeCompareBySparkSQL.java

修改人：刘思阳
修改内容：修改ftpUrl
所属模块：hbase
合入人：赵喆
合入时间：2017-11-8

修改ftpUrl返回值

---

HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CapturePictureSearchServiceImpl.java

修改人 ： 陈柯
修改内容：修改option的人车类型
所属模块： HBase
合入人：赵喆
合入时间：2017-11-10

修改option的人车类型

---

Distribution/bin/put-criminal-to-hbase-and-createjson-for-es.sh
HBase/src/main/java/com/hzgc/hbase/dynamicrepo/CaptureHistory.java
HBase/src/main/java/com/hzgc/hbase/putdata/putCriminalToHbase.java

修改人：陈柯
修改内容： 添加导入图片方法及其脚本
所属模块：Hbase
合入人：赵喆
合入时间：2017-11-13

添加导入图片方法及其脚本

---

Distribution/bin/create-static-repos.sh
Distribution/pom.xml
Distribution/src/main/assembly/assembly.xml
HBase/src/main/java/com/hzgc/hbase/staticrepo/tablecreate/CreateSrecordTable.java
HBase/src/main/java/com/hzgc/hbase/staticrepo/tablecreate/CreateStaticRepoTable.java
HBase/src/main/java/com/hzgc/hbase/util/HBaseHelper.java
HBase/src/main/resources/srecord-table.properties
HBase/src/main/resources/static-table.properties
pom.xml

修改人 ： 李第亮
修改内容： 
1，使用脚本建立静态库的表格修改（代码和脚本的修改）。
2，把无用的模块HBase2Es 从父pom 文件中删除，同时删除收集jar 包时对hbase2es jar 包的收集。
所属模块： Distribution 和 HBase ， Dubbo
合入人：赵喆
合入时间：2017-11-14

Fixed create static repos

---

Distribution/bin/bulk-Residentdata-to-hbase-and-createjson-for-es.sh
Distribution/bin/bulk-criminaldata-to-hbase-and-createjson-for-es.sh
Distribution/bin/check-kafka-to-parquet.sh
Distribution/bin/restart-kafka-to-parquet.sh
HBase/pom.xml
HBase/src/main/java/com/hzgc/hbase/putdata/putResidentToHbase.java

修改人：陈柯
修改内容：
Distribution模块：增加自动重启kafkatoparquet脚本、导入数据脚本
Hbase模块：导入数据脚本、导入居民数据代码
合入人：赵喆
合入时间：2017-11-16
分支：master

增加自动重启kafkatoparquet脚本、导入数据脚本、导入居民数据代码

---

Cluster/src/assembly/assembly.xml
Cluster/src/main/resources/log4j.properties
Distribution/src/assembly/assembly.xml
Dubbo/src/assembly/assembly.xml
Dubbo/src/main/resources/log4j.properties
FtpServer/bin/start-ftpserver.sh
FtpServer/pom.xml
FtpServer/src/assembly/assembly.xml
Service/src/assembly/assembly.xml

修改人：刘思阳
修改内容：添加本模块jar到lib目录、ftp模块删除hbase-client依赖
所属模块：all
合入人：赵喆
合入时间：2017-11-17

添加本模块jar到lib目录、ftp模块删除hbase-client依赖

---

Cluster/bin/check-kafka-to-parquet.sh
Cluster/bin/restart-kafka-to-parquet.sh
Cluster/bin/start-kafka-to-parquet.sh

修改人：陈柯
修改内容：因模块变动，修改kafkatoparquet启动脚本
所属模块：cluster
合入人：赵喆
合入时间：2017-11-17

因模块变动，修改脚本

---

Cluster/bin/add-udf-to-hive.sh

修改人：乔凯峰
修改内容：增加从hive端注册udf函数脚本，并将udf-1.5.0.jar加入到项目lib中
所属模块：cluster
合入人：赵喆
合入时间：2017-11-17

增加添加udf函数到hive脚本

---

Cluster/bin/config-merge-parquet-file.sh

修改人：李第亮。
修改内容：添加自动配置小服务定时的脚本
所属模块：cluster
合入人：赵喆
合入时间：2017-11-17

一键配置启动合并小文件服务的脚本。

---

Cluster/bin/load-parquet-files.sh

修改人：乔凯峰
修改内容： 修改加载数据中hbase-1.5.0.jar为service-1.5.0.jar
修改模块：cluster
合入人：乔凯峰
合入时间：2017-11-20

因hbase模块更名为service模块，修改加载数据脚本

---

Cluster/bin/start-kafka-to-parquet.sh

修改人：陈柯
修改内容：Cluster模块：任务启动脚本修改（任务依赖jar版本修改）
合入人：赵喆
合入时间：2017-11-29

修改start-kafka-to-parquet脚本中的jar包的版本号

---

pom.xml

修改人：李第亮
修改内容： parent-pom.xml 中kafka 版本更改
合入人：赵喆
合入时间：2017-11-29

change kafka version

---

Cluster/bin/load-parquet-files.sh

修改人：乔凯峰
修改内容：cluster模块：修改kafka版本
合入人：赵喆
合入时间：2017-11-29

修改load data脚本 kafka版本

---

Distribution/src/assembly/assembly.xml
FtpServer/src/main/java/com/hzgc/ftpserver/local/LocalOverFtpServer.java
FtpServer/src/main/java/com/hzgc/ftpserver/local/LocalSTOR.java
FtpServer/src/main/java/com/hzgc/ftpserver/util/LoggerConfig.java

修改人：刘思阳
修改模块：FTP
修改内容：FTP模块设置动态日志配置文件刷新时间
合入人：赵喆
合入时间：2017-11-30

FTP模块设置动态日志配置文件刷新时间

---

Cluster/bin/load-parquet-files.sh

修改人：乔凯峰
修改模块：cluster模块
修改内容：修改load-parquet-files.sh中cluster-1.5.0.jar包从common模块下lib目录加载
合入人：赵喆
合入时间：2017-12-1

修改load data脚本

---

Cluster/src/main/resources/log4j.properties
Dubbo/src/main/resources/log4j.properties
FtpServer/pom.xml
FtpServer/src/main/java/com/hzgc/ftpserver/producer/ProducerOverFtp.java
FtpServer/src/main/java/com/hzgc/ftpserver/util/CounterTest.java
Service/src/main/resources/log4j.properties

修改人：刘思阳
修改模块：FTP、Service、Cluster、Dubbo
修改内容：删除Dubbo、Cluster模块日志配置文件，
修改Service模块日志文件，
使用Metrics记录FTP发送Kafka数据执行次数
合入人：赵喆
合入时间：2017-11-30

修改Service模块日志文件，使用Metrics记录FTP发送Kafka数据执行次数

---

Cluster/pom.xml
pom.xml

修改人：李第亮
修改模块：Cluster
修改内容：
修改cluster 中kafka 相应的版本。
合入人：赵喆
合入时间：2017-12-02

change kafka banban..

---

Cluster/pom.xml
Cluster/src/assembly/assembly.xml
Dubbo/pom.xml
Dubbo/src/assembly/assembly.xml
FtpServer/pom.xml
FtpServer/src/assembly/assembly.xml
JNI/pom.xml
Service/pom.xml
Service/src/assembly/assembly.xml

修改人：李第亮
修改模块： 所有模块的
修改内容： 项目重构，把所有项目自己编译出来的jar 包都放到 common 底下。
合入人：赵喆
合入时间：2017-12-4

to change then dependency scope of the    bigdata api jar.

---

Service/src/main/java/com/hzgc/service/dynamicrepo/ParseByOption.java

修改人：乔凯峰
修改模块：service 
修改内容：修改以图搜图人脸属性过滤条件
合入人：赵喆
合入时间：2017-12-4
合入分支：master    请检视合入

完善以图搜图人脸属性过滤条件

---

Service/src/main/java/com/hzgc/service/putdata/PutResidentToHbase.java

修改人：曹大报
修改模块：service
修改内容：修改PutToHbase日志打印
合入人：赵喆
合入时间：2017-12-4

修改PutToHbase日志打印

---

Cluster/bin/schema-merge-final-table-crash.sh
Cluster/bin/schema-merge-final-table.sh
Cluster/bin/schema-merge-parquet-file.sh

修改人：李第亮
修改模块：cluster
修改内容：脚本Bug 修复。
合入人：赵喆
合入时间：2017-12-6

Change script

---

Service/bin/add-udf.sh

修改add-udf中读取udf的jar包路径

---

Dubbo/bin/start-dubbo.sh
FtpServer/bin/start-ftpserver.sh
Service/bin/create-static-repos.sh
Service/src/main/resources/srecord-table.properties
Service/src/main/resources/static-table.properties

修改人：李第亮
修改内容：ftp, server, 脚本修改。
合入人：赵喆
合入时间：2017-12-06
分支：master

ftp and create static repo.

---

Service/bin/create-dynamic-table.sh
Service/src/main/resources/jdbc.properties

修改人：乔凯峰
修改内容：service模块：修改创建表脚本中特征值类型，以及jdbc url的值
合入人：赵喆
合入时间：2017-12-07
分支：master

修改创建表脚本中特征值类型，以及jdbc url

---

FtpServer/src/main/java/com/hzgc/ftpserver/util/Download.java
Service/pom.xml

修改人：李第亮
修改内容：Server 模块静态信息库少jar 包。
合入人：赵喆
合入时间：2017-12-11
分支：master

bug fixed in less pingyin jar in server

---

Service/src/main/java/com/hzgc/service/dynamicrepo/ParseByOption.java

修改人：乔凯峰
修改内容：service模块，以图搜图中添加判断当人脸属性的属性值为0时不添加此属性到过滤条件
合入人：赵喆
合入时间：2017-12-12
分支：master

修改人脸属性过滤条件bug

---

Cluster/bin/start-face-add-alarm-job.sh
Cluster/bin/start-face-offline-alarm-job.sh
Cluster/bin/start-face-recognize-alarm-job.sh
Cluster/bin/start-kafka-to-es.sh
Cluster/bin/start-kafka-to-parquet.sh
Cluster/bin/start-new-kafka-to-parquet.sh

修改人： c陈柯
修改内容：删除脚本中ftpserver-core的jar包依赖
修改模块：cluster
合入人：赵喆
合入时间：2017-12-19

删除脚本中ftpserver-core的jar包依赖

---

Service/bin/create-kafka-topic.sh

修改人： 马燊偲
修改内容：修改创建kafka topic脚本，解决创建topic不成功的问题
修改模块：service
合入人：赵喆
合入时间：2017-12-20

修改创建kafka topic脚本

---

Cluster/bin/config-clusterconf.sh
Distribution/bin/config-projectconf.sh
FtpServer/bin/config-ftpconf.sh
Service/bin/config-serviceconf.sh

修改人： 马燊偲 & 曹大报
修改内容：修改项目配置文件与集群配置文件的耦合，项目脚本中所有配置从项目配置文件中读取。
修改模块：common/cluster/ftp/service
合入人：赵喆
合入时间：2017-12-22

修改项目配置文件与集群配置文件的耦合

---

FtpServer/src/main/java/com/hzgc/ftpserver/command/impl/STOR.java
FtpServer/src/main/java/com/hzgc/ftpserver/producer/RocketMQProducer.java
FtpServer/src/main/resources/cluster-over-ftp.properties
FtpServer/src/main/resources/rocketmq.properties
Service/bin/create-kafka-topic.sh

修改人： 刘思阳
修改内容：修改FTP发送MQ的topic，修改发送MQ的内容为ftpUrl
修改模块：ftp
合入人：赵喆
合入时间：2017-12-27

修改FTP发送MQ的topic，修改发送MQ的内容为ftpUr

---

Cluster/bin/config-clusterconf.sh
Distribution/bin/config-projectconf.sh
Distribution/src/resources/project-conf.properties
FtpServer/bin/config-ftpconf.sh
FtpServer/src/main/java/com/hzgc/ftpserver/command/impl/STOR.java
FtpServer/src/main/java/com/hzgc/ftpserver/producer/RocketMQProducer.java
FtpServer/src/main/resources/rocketmq.properties
Service/bin/config-serviceconf.sh
Service/bin/create-kafka-topic.sh

修改人：曹大报、刘思阳
修改内容：
FtpServer、Cluster、Service、Distribution模块
合入人：赵喆
合入时间：2017-12-27
分支：v1.5.2

修改项目脚本、还原FTP发MQ的Topic

---

Dubbo/bin/start-dubbo.sh

修改人：李第亮
修改内容：
Dubbo启动脚本
合入人：赵喆
合入时间：2017-12-28
分支：v1.5.2

修改dubbo启动脚本

---

FtpServer/src/main/java/com/hzgc/ftpserver/FTP.java
FtpServer/src/main/java/com/hzgc/ftpserver/command/impl/STOR.java
FtpServer/src/main/java/com/hzgc/ftpserver/common/FtpUtil.java
FtpServer/src/main/java/com/hzgc/ftpserver/filesystem/nativefs/impl/NativeFtpFile.java
FtpServer/src/main/java/com/hzgc/ftpserver/impl/PassivePorts.java
FtpServer/src/main/java/com/hzgc/ftpserver/producer/ProducerOverFtp.java
FtpServer/src/main/java/com/hzgc/ftpserver/producer/RocketMQProducer.java
FtpServer/src/main/java/com/hzgc/ftpserver/queue/BufferQueue.java
FtpServer/src/main/java/com/hzgc/ftpserver/queue/DataProcess.java
FtpServer/src/main/java/com/hzgc/ftpserver/queue/QueueUtil.java
FtpServer/src/main/resources/log4j.properties

修改人： 刘思阳
修改内容：整理FTP代码与日志
修改模块：ftp
合入人：赵喆
合入时间：2017-12-28

整理FTP代码与日志

---

Distribution/bin/facecomp-daemon.sh

修改人： 李第亮
修改内容：修改守护进程脚本Bug，适配ftp 进程名字的修改。
修改模块：common
合入人：赵喆
合入时间：2017-12-28

适配ftp 进程名字的修改

---

Cluster/src/main/scala/com/hzgc/cluster/consumer/KafkaToParquet.scala

修改人： 陈柯
修改内容： 修改保存偏移量的地址
修改模块：cluster
合入人：赵喆
合入时间：2018-1-2

 修改保存偏移量地址

---

Cluster/bin/config-clusterconf.sh
Cluster/bin/start-kafka-to-parquet.sh
Distribution/src/resources/project-conf.properties
FtpServer/bin/config-ftpconf.sh
Service/bin/change-data-featuretype.sh
Service/src/main/java/com/hzgc/service/dynamicrepo/ParseByOption.java
Service/src/main/java/com/hzgc/service/staticrepo/ChangeFeatureByPkey.java
Service/src/main/java/com/hzgc/service/util/JDBCUtil.java
Service/src/test/resources/es-config.properties
Service/src/test/resources/log4j.properties

修改人： 曹大报
修改内容： 
1、添加根据pkey修改图片特征值，并同步到HBase和ES代码和脚本（已测）
2、修改kafkaToParquet脚本（改为client模式）
3、修改项目脚本（项目配置文件中新增配置项支持可配）
4、修改搜图部分日志级别，JDBC日志输出
修改模块：cluster
合入人：赵喆
合入时间：2018-1-4

 添加根据pkey修改特征值代码、修改项目脚本、修改JDBCUtil打印日志

---

Service/src/main/java/com/hzgc/service/dynamicrepo/ParseByOption.java

修改人： 刘思阳
修改内容： 修改以图搜图SQL拼接
修改模块：Service
合入人：赵喆
合入时间：2018-1-4

修改以图搜图SQL拼接

---

Service/src/main/java/com/hzgc/service/util/JDBCUtil.java

修改人： 刘思阳
修改内容： 捕捉JDBC连接异常
修改模块：Service
合入人：赵喆
合入时间：2018-1-4

捕捉JDBC连接异常

---

Service/src/main/java/com/hzgc/service/dynamicrepo/CapturePictureSearchServiceImpl.java

修改人： 刘思阳
修改内容： 修改属性统计接口（修改ES过滤方法）
修改模块：service
合入人：赵喆
合入时间：2018-1-10

修改属性统计接口（修改ES过滤方法）

---

FtpServer/src/main/java/com/hzgc/collect/expand/receiver/ReceiverScheduler.java

修改人：陈柯
修改内容：
FtpServer模块：ReceiverScheduler文件添加备注和报错输出
合入人：赵喆
合入时间：2018-01-26
分支：ceph

ReceiverScheduler文件添加备注和报错输出

---

FtpServer/src/main/java/com/hzgc/collect/expand/receiver/ReceiverScheduler.java

修改人：陈柯
修改内容：
FtpServer模块：ReceiverScheduler文件修改当第一次初始化receiver时的代码
合入人：赵喆
合入时间：2018-01-26
分支：ceph

ReceiverScheduler文件修改当第一次初始化receiver时的代码

---

FtpServer/src/main/java/com/hzgc/collect/expand/util/ProperHelper.java

修改人：马燊偲
修改内容：修改ProperHelper类：添加判断：若代码中存在key键的变量，但配置文件中不存在，会报错。
修改模块：FtpServer-util
合入人：赵喆
合入时间：2018-01-27
分支：ceph

添加判断：若代码中存在key键的字段，但配置文件中不存在，会报错。

---

FtpServer/src/main/java/com/hzgc/ftpserver/command/impl/STOR.java
FtpServer/src/main/java/com/hzgc/ftpserver/producer/RocketMQProducer.java
FtpServer/src/main/resources/rocketmq.properties

修改人： 刘思阳
修改内容： 1.5.2分支MQProducer发送图片数据改为发送ftpUrl
修改模块：ftp
合入人：赵喆
合入时间：2018-1-31

1.5.2分支MQProducer发送图片数据改为发送ftpUrl

---

Cluster/src/main/resources/log4j.properties

修改人：刘思阳
修改内容：Cluster模块添加log4j.properties文件
修改模块：Cluster
修改时间：2018-2-7
合入人：赵喆
分支：master

Cluster add log4j.properties

---

FtpServer/src/main/java/com/hzgc/collect/expand/receiver/ReceiverScheduler.java
FtpServer/src/test/java/com/hzgc/collect/expand/receiver/ReceiverSchedulerTest.java

修改人：陈柯
修改内容：为ReceiverScheduler添加测试类ReceiverSchedulerTest
修改模块：ftpserver
修改时间：2018-02-08
合入人：赵喆
分支：ceph

添加ReceiverSchedulerTest测试类ReceiverSchedulerTest

---

FtpServer/src/test/java/com/hzgc/collect/expand/receiver/ReceiverSchedulerTest.java

修改人：陈柯
修改内容：修改ReceiverSchedulerTest测试类
修改模块：ftpserver
修改时间：2018-02-08
合入人：赵喆
分支：ceph

修改ReceiverSchedulerTest测试类

---

Service/src/main/java/com/hzgc/service/dynamicrepo/CptureNumberImpl.java
Service/src/test/java/com/hzgc/service/dynamicrepo/CptureNumberImpTest1.java

修改人：陈柯
修改内容：
修改统计动态库数量timeSoltNumber方法，使统计数量正确
修改模块：service模块
合入人：赵喆
合入时间：2018-03-02
分支：master

修改统计动态库数量timeSoltNumber方法，使统计数量正确

---

Service/src/main/java/com/hzgc/service/dynamicrepo/CptureNumberImpl.java

修改人：陈柯
修改内容：向数据可视化调用方法添加锁，保证数据有序
修改模块：service模块
合入人：赵喆
合入时间：2018-03-15
分支：master

向数据可视化调用方法添加锁，保证数据有序

---

Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/CapturePictureSearchService.java
Service/src/main/java/com/hzgc/service/dynamicrepo/CapturePictureSearchServiceImpl.java

修改人：陈柯
修改内容：修改原定getCaptureHistory接口
修改模块：dubbo、service模块
合入人：赵喆
合入时间：2018-03-19
分支：multi-picture-search

修改原定getCaptureHistory接口

---

Service/src/main/java/com/hzgc/service/dynamicrepo/CaptureHistory.java
Service/src/main/java/com/hzgc/service/dynamicrepo/CapturePictureSearchServiceImpl.java
Service/src/test/java/com/hzgc/service/dynamicrepo/CptureNumberImpTest1.java

修改人：陈柯
修改内容：增加历史搜索时，搜索条件有ipcid但是不按照ipcid排序的情况
修改模块：service模块
合入人：赵喆
合入时间：2018-03-20
合入分支：multi-picture-search

增加历史搜索时，搜索条件有ipcid但是不按照ipcid排序的情况

---

Dubbo/src/main/java/com/hzgc/dubbo/staticrepo/ObjectInfoHandler.java
Service/src/main/java/com/hzgc/service/putdata/PutCriminalToHbase.java
Service/src/main/java/com/hzgc/service/putdata/PutDataToHBase.java
Service/src/main/java/com/hzgc/service/putdata/PutResidentToHbase.java
Service/src/main/java/com/hzgc/service/staticrepo/ChangeFeatureByPkey.java
Service/src/main/java/com/hzgc/service/staticrepo/ObjectInfoHandlerImpl.java

修改人：李第亮
修改内容：静态信息库Bug 修改
修改模块：dubbo service
合入人：赵喆
合入时间：2018-03-20
分支：ceph

Multi picture search

---

Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/CapturePictureSearchService.java
Service/pom.xml
Service/src/main/java/com/hzgc/service/dynamicrepo/CaptureHistory.java
Service/src/test/java/com/hzgc/service/dynamicrepo/CptureNumberImpTest1.java

修改人：陈柯
修改内容：修改历史查询调试问题
修改模块：service模块
合入人：赵喆
合入时间：2018-03-20
合入分支：multi-picture-search

修改历史查询调试问题

---

Cluster/bin/schema-merge-final-table-crash.sh
Cluster/bin/schema-merge-final-table.sh
Cluster/bin/schema-merge-parquet-file.sh
Cluster/bin/schema_merge_final_table.job
Cluster/bin/schema_merge_final_table_crash.job
Cluster/bin/schema_merge_parquet_file.job
Cluster/bin/start-face-offline-alarm-job.sh
Cluster/bin/start_face_offline_alarm_job.job
Cluster/bin/timed-task.sh
Service/bin/create-es-index.sh

修改人：曹大报
修改内容：
1、结合Azkaban修改定时任务脚本，job压缩包放在共享目录下（\集群搭建\Azkaban定时任务目录下）
2、将dynamicshow创建索引脚本添加到一键配置中
3、添加定时任务job文件，结合Azkaban添加生成定时任务zip文件脚本（已测试）
修改模块：cluster、service
合入人：赵喆
合入时间：2018-03-10
分支：master

 结合Azkaban修改定时任务脚本，将dynamicshow创建索引脚本添加到一键配置中

---

Service/src/main/java/com/hzgc/service/dynamicrepo/CaptureHistory.java
Service/src/test/java/com/hzgc/service/dynamicrepo/CptureNumberImpTest1.java

修改人：陈柯
修改内容：修改captureHistory方法调试出现的bug
修改模块：service模块
合入人：赵喆
合入时间：2018-03-20
合入分支：master

将修改合入master分支

---

Service/src/main/java/com/hzgc/service/dynamicrepo/CaptureHistory.java
Service/src/test/java/com/hzgc/service/dynamicrepo/CptureNumberImpTest1.java

修改人：陈柯
修改内容： 修改抓拍历史统计数量的方式
修改模块：service模块
合入人：赵喆
合入时间：2018-03-22
合入分支：master

 修改抓拍历史统计数量的方式

---

Service/bin/add-phoenix-udf.sh
Service/bin/create-static-phoneix-table.sh
Service/src/main/resources/sql/phoenix-udf.sql
Service/src/main/resources/sql/staticrepo.sql

修改人：李第亮
修改内容：静态信息库Phoenix 建表语句
修改模块：Service
合入人：赵喆
合入时间：2018-03-22
分支：master

静态信息库Phoenix 建表语句

---

Service/src/main/java/com/hzgc/service/dynamicrepo/CaptureHistory.java
Service/src/main/java/com/hzgc/service/dynamicrepo/CapturePictureSearchServiceImpl.java
Service/src/test/java/com/hzgc/service/dynamicrepo/CptureNumberImpTest1.java

修改人：陈柯
修改内容：修改抓拍历史查询数量出错
修改模块：service模块
合入人：赵喆
合入时间：2018-03-23
合入分支：master

修改抓拍历史查询数量出错

---

Service/src/main/java/com/hzgc/service/staticrepo/ParseByOption.java

修改人：李第亮
修改内容：静态信息库更新接口，sql 排序条件拼接Bug 修改.
修改模块：Service
合入人：赵喆
合入时间：2018-03-23
分支：master

更新排序sql 拼接.

---

Dubbo/src/main/java/com/hzgc/dubbo/address/FtpShow.java
Dubbo/src/main/java/com/hzgc/dubbo/address/FtpSubscription.java
Service/src/main/java/com/hzgc/service/address/FtpShowImpl.java
Service/src/main/java/com/hzgc/service/address/FtpSubscriptionImpl.java
Service/src/main/resources/spring-context.xml

修改人：刘思阳
修改内容： 添加抓拍订阅演示实现类
修改模块：dubbo、service模块
合入人：赵喆
合入时间：2018-03-24
分支：master

添加抓拍订阅演示实现类

---

Service/src/main/java/com/hzgc/service/dynamicrepo/CaptureHistory.java

修改人：陈柯
修改内容：修改历史抓拍中人脸属性的判断
修改模块：service模块
合入人：赵喆
合入时间：2018-03-24
合入分支：master

修改历史抓拍中人脸属性的判断

---

Cluster/src/main/scala/com/hzgc/cluster/clustering/ResidentClustering.scala

修改人：彭聪
修改内容：修复聚类数据重复问题
修改模块：clustering
合入人：赵-喆
合入时间：2018-03-27
分支：master

修复聚类数据重复问题

---

Service/bin/config-serviceconf.sh
Service/src/main/resources/jdbc.properties

修改人：李第亮
修改内容：phoenix jdbc 地址一键配置
修改模块：service
合入人：赵-喆
合入时间：2018-03-27
分支：master

配置phoenix jdbc 地址.

---

Cluster/bin/create-schedule-job-to-zip.sh

修改人：陈柯
修改内容：添加自动生成定时任务的zip包的脚本
修改模块：cluster
合入人：赵喆
合入时间：2018-03-27
合入分支：master

添加自动生成定时任务的zip包的脚本

---

Dubbo/src/main/java/com/hzgc/dubbo/dynamicrepo/CapturePictureSearchService.java
Service/src/main/java/com/hzgc/service/dynamicrepo/CapturePictureSearchServiceImpl.java
Service/src/test/java/com/hzgc/service/dynamicrepo/CapturePictureSearchServiceTest.java

修改人：陈柯
修改内容：添加查询抓拍统计多设备接口和实现类以及测试类
修改模块：service模块
合入人：赵喆
合入时间：2018-03-28
合入分支：master

添加查询抓拍统计多设备接口和实现类以及测试类

---

Cluster/bin/config-clusterconf.sh
Cluster/bin/start-resident-clustering-job.sh
Cluster/src/main/resources/sparkJob.properties
Cluster/src/main/scala/com/hzgc/cluster/clustering/KMeansClustering.scala
Cluster/src/main/scala/com/hzgc/cluster/clustering/ResidentClustering.scala

修改人：彭聪
修改内容：修复脚本不能正确分发mysql bug，增加按连续出现天过滤代码
修改模块：clustering
合入人：赵-喆
合入时间：2018-03-29
分支：master

修复脚本不能正确分发mysql bug，增加按连续出现天过滤代码

---

Cluster/src/main/scala/com/hzgc/cluster/clustering/ResidentClustering.scala

修改人：彭聪
修改内容：增加数据库查询判空、以及数据去重
修改模块：clustering
合入人：赵-喆
合入时间：2018-03-29
分支：master

增加数据库查询判空、以及数据去重

---

Cluster/src/main/java/com/hzgc/cluster/consumer/PutDataToEs.java
Dubbo/src/main/java/com/hzgc/dubbo/attribute/Eyeglasses.java
Service/src/main/java/com/hzgc/service/dynamicrepo/CapturePictureSearchServiceImpl.java
Service/src/main/java/com/hzgc/service/dynamicrepo/DynamicTable.java

修改人：陈柯
修改内容：将eleglasses改成eyeglasses
修改模块：dubbo、service模块
合入人：赵喆
合入时间：2018-03-30
合入分支：master

将eleglasses改成eyeglasses

---

Service/src/main/java/com/hzgc/service/dynamicrepo/CaptureNumberImplTimer.java

修改人：陈柯
修改内容：将数据可视化接口每小时插入数据放入azkaban
修改模块：service模块
合入人：赵喆
合入时间：2018-04-10
合入分支：master

将数据可视化接口每小时插入数据放入azkaban

---

Service/pom.xml
Service/src/main/java/com/hzgc/service/staticrepo/ObjectInfoHandlerImpl.java
Service/src/main/java/com/hzgc/service/staticrepo/ObjectInfoInnerHandlerImpl.java
Service/src/main/java/com/hzgc/service/staticrepo/PhoenixJDBCHelper.java
Service/src/main/java/com/hzgc/service/staticrepo/PrisonServiceImpl.java
Service/src/main/resources/dubbo.properties
Service/src/main/resources/jdbc.properties
Service/src/test/java/com/hzgc/service/staticreposuite/StaticJDBCSuite.java

修改人： 李第亮
修改内容：
1，静态库数据库连接池的使用，使用阿里的druid 连接池。
修改模块：service模块, 
合入人：赵喆
合入时间：2018-04-17
合入分支：master

静态信息库数据库连接池的使用

---

Service/src/main/java/com/hzgc/service/staticrepo/ObjectInfoHandlerImpl.java
Service/src/main/java/com/hzgc/service/staticrepo/ParseByOption.java

修改人： 李第亮
修改内容：
1，修改更新接口，更新接口使用的ArrayList 和HashMap线程不安全，需要改成CopyOnWriteArray 和ConcurrentHashMap.
修改模块：service模块,
合入人：赵喆
合入时间：2018-04-23
合入分支：master

修改接口线程不安全Bug 修复

---

FtpServer/bin/start-ftpserver.sh

修改人： 李第亮
修改内容：
1，给ftp 进程所在的机器添加定时清理内存的脚本.
修改模块：ftp模块,
合入人：赵喆
合入时间：2018-04-26
合入分支：master

给ftp 进程所在的机器添加定时清理内存的脚本

---

Service/src/main/java/com/hzgc/service/dynamicrepo/CaptureNumberImpl.java

修改人： 李第亮
修改内容：
1，修改静态库指定平台ID 下，各个对象类型下的人总数统计接口。
2，修改动态库抓拍总数和今天抓拍总数接口。
修改模块：ftp模块,
合入人：赵喆
合入时间：2018-04-26
合入分支：master

动态库和静态库数量统计接口修改

---

Dubbo/src/main/java/com/hzgc/dubbo/staticrepo/PrisonService.java
Service/src/main/java/com/hzgc/service/staticrepo/PrisonServiceImpl.java

修改人：李第亮
修改内容：重置所有静态库对象的位置
修改模块：cluster
合入人：赵喆
合入时间：2018-05-07
合入分支：master

重置所有静态库对象的位置

---

Cluster/bin/create-schedule-job-to-zip.sh

修改人:尹航
修改内容:azkaban中需要的job打包成zip的脚本
修改模块：cluster
合入人：赵喆
合入时间：2018-05-07
合入分支：guizhou_2.1.0

修改azkaban中需要的job打包成zip的脚本

---

Service/src/main/java/com/hzgc/service/dynamicrepo/CaptureNumberImpl.java

修改人：陈柯
修改内容：将定时搜索代码改为使用聚合函数查询
修改模块：service
合入人：赵喆
合入时间：2018-05-17
合入分支：master

将定时搜索代码改为使用聚合函数查询
